name: Update Fee TVL Data
on:
  workflow_dispatch:

jobs:
  update_symbol_list:
    name: Update Fee TVL Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          GKEY: ${{ secrets.GKEY }}
        run: |
          python fee_tvl_data.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add logs
          git commit -m "Updated Fee TVL Data on `date` with GitHub Actions" || echo "No Changes to Commit"
          git push origin main || echo "No Changes to Commit"